# Generated by Django 4.2.5 on 2023-09-19 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_rename_user_cliente_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='cliente',
            new_name='user',
        ),
    ]
