# Generated by Django 4.2.4 on 2023-09-07 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={},
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='Estado_cliente',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='Estado_Empleado',
        ),
        migrations.AlterModelTable(
            name='cliente',
            table=None,
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado_cliente',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Bloqueado', 'Bloqueado')], default='Activo', max_length=20, verbose_name='Estado del cliente'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='estado_empleado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Bloqueado', 'Bloqueado')], default='Activo', max_length=20, verbose_name='Estado del empleado'),
        ),
    ]
