# Generated by Django 4.2.4 on 2023-09-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='image',
            field=models.ImageField(default='productos/default.jpg', upload_to='productos/', verbose_name='Imagen del producto'),
        ),
    ]
