# Generated by Django 4.2.5 on 2023-09-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_producto_slug'),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Productos',
            field=models.ManyToManyField(through='carts.CartProducts', to='core.producto'),
        ),
    ]
