# Generated by Django 4.2.4 on 2023-09-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PQRS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoPQRS', models.CharField(choices=[('Pregunta', 'Pregunta'), ('Queja', 'Queja'), ('Reclamo', 'Reclamo'), ('Sugerencia', 'Sugerencia')], max_length=20, verbose_name='Tipo de PQRS')),
                ('EstadoPQRS', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Proceso', 'En Proceso'), ('Resuelta', 'Resuelta')], default='Pendiente', max_length=20, verbose_name='Estado de PQRS')),
                ('fechaPQRS', models.DateField(verbose_name='Fecha de PQRS')),
                ('DescripcionPQRS', models.TextField(max_length=100, verbose_name='Descripción de PQRS')),
            ],
            options={
                'verbose_name': 'PQRS',
                'verbose_name_plural': 'PQRSs',
                'db_table': 'pqrs',
                'ordering': ['tipoPQRS'],
            },
        ),
    ]
